### ISSUE TITLE
Unable to get list of campaigns for Cause

### ISSUE THREAD

**Issue by mknooihuisen** [Tiltify/api#21] opened 2021-02-04 22:28 UTC
I have been receiving a 401 error on GET requests to `https://tiltify.com/api/v3/causes/1171/campaigns` both using my applications bearer token and one I generated using Oauth2.  So far as I can tell this should be publicly accessible since it is on the website and also appears to be listed in the permissions API as visible.

Thanks in advance for any help!

**Comment by weinerm** [comment] 2021-04-14 14:26
I can confirm the same 401 error. Any updates from the devs?

**Comment by Eein** [comment] 2021-04-15 21:24
Hello! 

Sorry for the extremely delayed response - after taking a look through our code, there was a business requirement to not expose this data to users, and it seems like the limitation that drove that decision hasn't met a resolution.

On our public facing website, we are using some new API's for handling the cause campaigns listings that aren't quite ready for public consumption.

We have plans to add cause campaigns (and other campaign) look-ups in a future API, but we currently don't have a public way to provide this at this time.

I'll put an internal request to have this looked at for public consumption in our new public API; unfortunately we dont have a firm date on when that will be released...

**Comment by rbitting** [comment] 2021-08-09 19:47
I'm encountering this same issue on the `/fundraising-events/:id/campaigns` endpoint. Is this data still not publicly available?

**Comment by rbitting** [comment] 2021-11-17 21:28
@mknooihuisen Sorry for the late response. Yes, that resolved the issue for me.

**Closed** 2021-11-17 21:42 UTC
Labels: Feature Request
